#@data/values-schema
#! This file contains default config values
#! To override these values, use override files
---
namespace:
  name: giant-app
  #! Set to null to omit Namespace resource
  #@schema/type any=True
  #@schema/nullable
  owner: null

giantApp:
  name: giant-app
  message: "default from package"

  memRequest: "128Mi"
  cpuRequest: "500m"
  memLimit: "256Mi"
  cpuLimit: "1000m"

  #@schema/desc "Set hostname and domain to null to omit Ingress resource"
  ingress:
    #@schema/type any=True
    #@schema/nullable
    hostname: null
    #@schema/type any=True
    #@schema/nullable
    domain: null
    #@schema/type any=True
    #@schema/nullable
    class: null
    secret:
      #@schema/type any=True
      #@schema/nullable
      certificate: null
      #@schema/type any=True
      #@schema/nullable
      privateKey: null

