apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: metapackage.corp.com.1.0.0
spec:
  refName: metapackage.corp.com
  releasedAt: "2023-07-10T21:57:16Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: taplab.azurecr.io/packaging-demo/metapackage@sha256:6df33e899b331179c52beed99a8903026d0adae47bcf3e9bc174fe4889b8d025
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        giantApp:
          additionalProperties: false
          properties:
            cpuLimit:
              default: 1000m
              type: string
            cpuRequest:
              default: 500m
              type: string
            deploymentType:
              default: ""
              description: 'Valid values: knative or core.'
              type: string
            ingress:
              additionalProperties: false
              description: Set hostname and domain to null to omit Ingress resource
              properties:
                class:
                  default: null
                  nullable: true
                domain:
                  default: null
                  nullable: true
                hostname:
                  default: null
                  nullable: true
                secret:
                  additionalProperties: false
                  properties:
                    certificate:
                      default: null
                      nullable: true
                    privateKey:
                      default: null
                      nullable: true
                  type: object
              type: object
            memLimit:
              default: 256Mi
              type: string
            memRequest:
              default: 128Mi
              type: string
            name:
              default: giant-app
              type: string
          type: object
        helloApp:
          additionalProperties: false
          properties:
            cpuLimit:
              default: 1000m
              type: string
            cpuRequest:
              default: 500m
              type: string
            deploymentType:
              default: ""
              description: 'Valid values: knative or core.'
              type: string
            ingress:
              additionalProperties: false
              description: Set hostname and domain to null to omit Ingress resource
              properties:
                class:
                  default: null
                  nullable: true
                domain:
                  default: null
                  nullable: true
                hostname:
                  default: null
                  nullable: true
                secret:
                  additionalProperties: false
                  properties:
                    certificate:
                      default: null
                      nullable: true
                    privateKey:
                      default: null
                      nullable: true
                  type: object
              type: object
            memLimit:
              default: 256Mi
              type: string
            memRequest:
              default: 128Mi
              type: string
            message:
              default: ""
              description: Name used in hello message from app when app is pinged.
              type: string
            name:
              default: hello-app
              type: string
          type: object
        installConfig:
          additionalProperties: false
          properties:
            serviceAccount:
              default: metapackage-sa
              type: string
          type: object
        namespace:
          additionalProperties: false
          properties:
            name:
              default: apps
              type: string
            owner:
              default: null
              description: Set to null to omit Namespace resource
              nullable: true
          type: object
        profile:
          default: full
          type: string
      type: object
  version: 1.0.0
