apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: giant-app.corp.com.3.5.1
spec:
  refName: giant-app.corp.com
  releasedAt: "2023-07-11T13:27:58Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: taplab.azurecr.io/packaging-demo/giant-app@sha256:47a56cc5dab47ad3f74f1de78b92e7844b2b132a2720ccc13668a9b2780c977a
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        giantApp:
          additionalProperties: false
          properties:
            cpuLimit:
              default: 1000m
              type: string
            cpuRequest:
              default: 500m
              type: string
            deploymentType:
              default: knative
              description: 'Valid values: knative or core.'
              type: string
            ingress:
              additionalProperties: false
              description: Set hostname and domain to null to omit Ingress resource
              properties:
                class:
                  default: null
                  nullable: true
                domain:
                  default: null
                  nullable: true
                hostname:
                  default: null
                  nullable: true
                secret:
                  additionalProperties: false
                  properties:
                    certificate:
                      default: null
                      nullable: true
                    privateKey:
                      default: null
                      nullable: true
                  type: object
              type: object
            memLimit:
              default: 256Mi
              type: string
            memRequest:
              default: 128Mi
              type: string
            name:
              default: giant-app
              type: string
          type: object
        namespace:
          additionalProperties: false
          properties:
            name:
              default: giant-app
              type: string
            owner:
              default: null
              nullable: true
          type: object
      type: object
  version: 3.5.1
