apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: hello-app.corp.com.1.2.3
spec:
  refName: hello-app.corp.com
  releasedAt: "2023-07-10T17:59:31Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: taplab.azurecr.io/packaging-demo/hello-app@sha256:5ad8f9e2022aefe75d80a55a167dbde0d7902d765fafc6607dd771d8f1a4af4e
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        helloApp:
          additionalProperties: false
          properties:
            cpuLimit:
              default: 1000m
              type: string
            cpuRequest:
              default: 500m
              type: string
            deploymentType:
              default: knative
              description: 'Valid values: knative or core.'
              type: string
            ingress:
              additionalProperties: false
              description: Set hostname and domain to null to omit Ingress resource
              properties:
                class:
                  default: null
                  nullable: true
                domain:
                  default: null
                  nullable: true
                hostname:
                  default: null
                  nullable: true
                secret:
                  additionalProperties: false
                  properties:
                    certificate:
                      default: null
                      nullable: true
                    privateKey:
                      default: null
                      nullable: true
                  type: object
              type: object
            memLimit:
              default: 256Mi
              type: string
            memRequest:
              default: 128Mi
              type: string
            message:
              default: default from package
              description: Name used in hello message from app when app is pinged.
              type: string
            name:
              default: hello-app
              type: string
          type: object
        namespace:
          additionalProperties: false
          properties:
            name:
              default: hello-app
              type: string
            owner:
              default: null
              description: Set to null to omit Namespace resource
              nullable: true
          type: object
      type: object
  version: 1.2.3
