apiVersion: kapp.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.40.0

rebaseRules:
  - path: [spec, paused]
    type: copy
    sources: [new, existing]
    resourceMatchers:
      - apiVersionKindMatcher: {apiVersion: packaging.carvel.dev/v1alpha1, kind: PackageInstall}
      - apiVersionKindMatcher: {apiVersion: kappctrl.k14s.io/v1alpha1, kind: App}

# This template rule is present by default kapp v0.54.0 onwards.
#
# This rule can be safely removed once we are not supporting any versions of Cluster Essentials
# that indirectly consume versions of kapp older than v0.54.0.
templateRules:
  - resourceMatchers:
      - apiVersionKindMatcher: {apiVersion: v1, kind: Secret}
    affectedResources:
      objectReferences:
        - path: [spec, values, {allIndexes: true}, secretRef]
          resourceMatchers:
            - apiVersionKindMatcher: {apiVersion: packaging.carvel.dev/v1alpha1, kind: PackageInstall}
