#@ load("@ytt:data", "data")

#@ if data.values.installConfig.serviceAccount == "metapackage-sa":
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metapackage-sa
  namespace: metapackage-install
  annotations:
    kapp.k14s.io/change-group: "rbac"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metapackage-cluster-role
  annotations:
    kapp.k14s.io/change-group: "rbac"
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metapackage-cluster-role-binding
  annotations:
    kapp.k14s.io/change-group: "rbac"
subjects:
  - kind: ServiceAccount
    name: metapackage-sa
    namespace: metapackage-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metapackage-cluster-role
#@ end