apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: hello-redis.corp.com
spec:
  release:
  - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp: {}
          template:
          - ytt:
              paths:
              - upstream
              - overlays
          - kbld: {}
      export:
      - imgpkgBundle:
          image: taplab.azurecr.io/packaging-demo/hello-redis
          useKbldImagesLock: true
        includePaths:
        - upstream
        - overlays
