apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: metapackage.corp.com.0.0.0
spec:
  refName: metapackage.corp.com
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: metapackage.corp.com
spec:
  displayName: metapackage
  longDescription: metapackage.corp.com
  shortDescription: metapackage.corp.com

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: metapackage
spec:
  packageRef:
    refName: metapackage.corp.com
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: metapackage-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
