apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageRepositoryBuild
metadata:
  creationTimestamp: "2023-06-21T20:53:59Z"
  name: metapackage-repo.corp.com
spec:
  export:
    imgpkgBundle:
      image: gcr.io/fe-ciberkleid/metapackage-repo
