apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: redis.corp.com.2.1.0
spec:
  refName: redis.corp.com
  releasedAt: "2023-07-06T12:18:08Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: index.docker.io/ciberkleid736/redis@sha256:af338857b96404e37ac2b071df1c7cd35689871ad769e421f6a7b3c7aa988dfc
      template:
      - ytt:
          paths:
          - upstream
          - overlays
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        helloApp:
          additionalProperties: false
          properties:
            name:
              default: hello-app
              type: string
          type: object
        namespace:
          additionalProperties: false
          properties:
            name:
              default: hello-app
              type: string
            owner:
              default: null
              description: Set to null to omit Namespace resource
              nullable: true
          type: object
      type: object
  version: 2.1.0
