#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:struct", "struct")

#@ def collect_values(data_values):
#@  namespace = "default"
#@  if hasattr(data.values, "namespace") and hasattr(data.values.namespace, "name") and data.values.namespace.name != "":
#@    namespace = data.values.namespace.name
#@  end
#@  values = {
#@    "helloApp": {
#@      "name": data.values.helloApp.name
#@    },
#@    "namespace": {
#@      "name": namespace
#@    }
#@  }
#@  return struct.encode(values)
#@ end
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: hello-redis
  namespace: metapackage-install
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting rbac"
spec:
  serviceAccountName: #@ data.values.installConfig.serviceAccount
  packageRef:
    refName: hello-redis.corp.com
    versionSelection:
      constraints: 2.1.0
  values:
    - secretRef:
        name: hello-redis-values
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-redis-values
  namespace: metapackage-install
stringData:
  values.yml: #@ yaml.encode(collect_values(data.values))