#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:struct", "struct")

#@ def collect_values(data_values):
#@  message = "big world"
#@  deploymentType = "knative"
#@  namespace = default
#@  if data.values.profile != "full":
#@    message = "small world"
#@    deploymentType = "core"
#@  end
#@  if hasattr(data.values, "namespace") and hasattr(data.values.namespace, "name") and data.values.namespace.name != "":
#@    namespace = data.values.namespace.name
#@  end
#@  if hasattr(data.values, "helloApp") and hasattr(data.values.helloApp, "message") and data.values.helloApp.message != "":
#@    message = data.values.helloApp.message
#@  end
#@  if hasattr(data.values, "helloApp") and hasattr(data.values.helloApp, "deploymentType") and data.values.helloApp.deploymentType != "":
#@    deploymentType = data.values.helloApp.deploymentType
#@  end
#@  values = {
#@    "helloApp": {
#@      "deploymentType": deploymentType,
#@      "name": data.values.helloApp.name,
#@      "message": message
#@    },
#@    "namespace": {
#@      "name": namespace
#@    }
#@  }

#@  return struct.encode(values)
#@ end
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: hello-app
  namespace: metapackage-install
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting rbac"
spec:
  serviceAccountName: #@ data.values.installConfig.serviceAccount
  packageRef:
    refName: hello-app.corp.com
    versionSelection:
      constraints: 1.2.3
  values:
    - secretRef:
        name: hello-app-values
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-app-values
  namespace: metapackage-install
stringData:
  values.yml: #@ yaml.encode(collect_values(data.values))