#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:struct", "struct")

#@ def collect_values(data_values):
#@  values = {
#@    "helloApp": {
#@      "name": data.values.helloApp.name
#@    },
#@    "namespace": {
#@      "name": data.values.namespace.name
#@    }
#@  }
#@  return struct.encode(values)
#@ end
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: redis
  namespace: metapackage-install
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting rbac"
spec:
  serviceAccountName: metapackage-install
  packageRef:
    refName: redis.corp.com
    versionSelection:
      constraints: 2.1.0
  values:
    - secretRef:
        name: redis-values
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-values
  namespace: #@ data.values.installConfig.namespace
stringData:
  values.yml: #@ yaml.encode(collect_values(data.values))